### PR TITLE
Add default value to the getter.

### PR DESCRIPTION
**Pull request by eggnaube**
Add the ability to define a default value when the getter method is called. If no key is found, the default value will be returned, otherwise null.

### CODE REVIEW

**Comment by simensen** [comment]
@eggnaube Thanks!

**Comment by eggnaube** [comment]
@simensen Is it possible to tag a new (minor) version? So we can install it via composer. And add PHP 5.5, 5.6 to the travis.yml. Tanks

**Comment by simensen** [comment]
@eggnaube I'm not opposed to tagging this. Would you mind adding 5.5 & 5.6 to the build matrix and sending a PR for that? I'll try to merge & tag soon after.

**Comment by simensen** [comment]
@eggnaube I've tagged v1.0.1! Let me know if things fail horribly. :)

**Pull request merged**
