### PR TITLE
Use php 7 typehinting

### PR DESCRIPTION
**Pull request by jenssegers**
I saw that the package now only provides support for PHP 7, so it would be nice to also take advantage of PHP 7's typehinting.

### CODE REVIEW

**Comment by jenssegers** [comment]
@dflydev did you see this already?

**Comment by peter279k** [comment]
The type hint looks good for me :+1: .

**Comment by peter279k** [comment]
@dflydev, can you look at this PR? Thanks.

**Comment by jenssegers** [comment]
Ping @dflydev

**Comment by jenssegers** [comment]
@dflydev any input on this PR?

**Comment by Narno** [comment]
Ping @simensen :-)

**Comment by jenssegers** [comment]
I give up :D

**Pull request closed without merging**
