### PR TITLE
Only support PHP 7.0 and above

### LINKED ISSUE #11: New major version that drops PHP5 support
Hi,

Would you consider releasing a new major with support for only PHP7?

If yes, I'll be happy to contribute.

### PR DESCRIPTION
**Pull request by martinssipenko**
Hi,

This pull requests closes #11 .

Here is a list of things I've changed:
- Require PHP version 7.0 and above;
- Changed old `array()` syntax to more modern `[]`;
- Updated `PSR-0` autoloading to `PSR-4`;
- Updated to PHPUnit version `6.0` and included in dev dependancies;
- Made changes to CI (run phpunit from vendor, removed php 5.3 from build matrix).

Let me know what you think about this.

I've not changed any interfaces, but potentially this can be done. Strict typing could be introduced if you think it makes sense.

### CODE REVIEW

**Comment by simensen** [comment]
@martinssipenko I'm happy to merge this as-is without strict typing. Are you happy with it? Or would you like to do something else before doing so?

**Comment by martinssipenko** [comment]
I think it's really your call wether or not to implement strict typing. As I see it, this would be the perfect time, given new major version is required.

**Comment by simensen** [comment]
@martinssipenko Sadly, I've not done anything at all with strict typing. So I don't have a lot to go on. That said, if you are capable of adding it, and willing to do so, we might as well.

**Comment by martinssipenko** [comment]
The only downside is that the interface will change, and users might need to update their code. Given this, if you think it makes sense, I'm happy to add it.

**Comment by simensen** [comment]
The only thing I'm not sure about is how strict typing would handle the `mixed` stuff. If that is easily handled/not a problem, then it is probably fine to update the interface for a major version upgrade. Will `mixed` be a problem?

**Comment by martinssipenko** [comment]
Not sure, so perhaps lets leave it out for now.

**Comment by simensen** [comment]
Go ahead and play with 2.0 dev for awhile and make sure it still works for you and then we can cut a tag for 2.0.0 if it all looks good.

**Comment by martinssipenko** [comment]
All the tests are green, so I'm assuming it should work as before. Also, no changes in logic were introduced. Simply replaced `array()` with `[]`, and if there would have been a bug introduced tests would have caught it.

**Comment by simensen** [comment]
Version 2.0.0 should now be available: https://packagist.org/packages/dflydev/dot-access-data

**Comment by martinssipenko** [comment]
Thank you! 👍

**Pull request merged**
